#!/bin/bash


source "aux/load"


if [[ $1 == "-devel" ]];then
    kurosh_webdev
fi

if [[ $1 == "-build" ]];then
    kurosh_webpub    
fi

if [[ $1 == "-apigen" ]];then
    packers_apigen
fi

if [[ $1 == "-wikigen" ]];then
    packers_wikigen
fi